#开发环境
server:
  port: 8181
spring:
  datasource:
    username: root
    password: caiyuntao@1992
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phone_store_demo
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true